import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = join(here, "..", "tokens");
const outDir = join(here, "..", "src");

// All declarations across the token files (later files can reference earlier ones).
const SOURCES = ["colors.css", "typography.css", "spacing.css"];
const declRe = /--([\w-]+)\s*:\s*([^;]+);/g;
const raw: Record<string, string> = {};
for (const file of SOURCES) {
  const css = readFileSync(join(tokensDir, file), "utf8");
  let m: RegExpExecArray | null;
  while ((m = declRe.exec(css))) raw[m[1]] = m[2].trim();
}

// Resolve every var(--x[, fallback]) reference, recursively, guarding cycles.
const varRe = /var\(\s*--([\w-]+)\s*(?:,[^)]*)?\)/g;
function resolve(value: string, seen: Set<string> = new Set()): string {
  return value.replace(varRe, (_full, name: string) => {
    if (!(name in raw) || seen.has(name)) return raw[name] ?? `var(--${name})`;
    return resolve(raw[name], new Set(seen).add(name));
  });
}

const tokens: Record<string, string> = {};
for (const [k, v] of Object.entries(raw)) tokens[k] = resolve(v);

mkdirSync(outDir, { recursive: true });
const banner =
  "// AUTO-GENERATED by scripts/gen-theme.ts — do not edit by hand.\n" +
  "// Source: packages/tokens/tokens/*.css\n\n";
const body =
  `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n\n` +
  "export type TokenName = keyof typeof tokens;\n";
writeFileSync(join(outDir, "tokens.generated.ts"), banner + body);
console.log(`gen-theme: wrote ${Object.keys(tokens).length} tokens`);
